### ISSUE TITLE
[Feature] Refactor question models with YAML

### ISSUE THREAD

**Issue by yo1995** [DukeMobileDevCenter/Jigsaw#37]
Instead of having a unified data structure for all question types, define protocols that makes questions conform to and use it to simplify question json models.

Note: this might violate `JSONEncoder` schema but is achievable with Firebase's less strict dictionary mapping schema.

**Comment by yo1995** [comment]
YAML is easier for clients to write and use. Maybe use it instead.

https://github.com/jpsim/Yams

**Comment by yo1995** [comment]
This should go after #26 , since it is a breaking change and might not be done before delivery.

**Comment by yo1995** [comment]
Changes ongoing - will wait for Ric's response on whether we should proceed. Will take another 2-3 hours to modify current model.

**Comment by yo1995** [comment]
This is done and I feel it is much better than previous JSON datasource. A example YAML file look like below:

```yml
gameName: "Education1"
version: "200826"
g1resURL: "https://today.duke.edu/2020/08/navigating-fake-news-how-americans-should-deal-misinformation-online"
g2resURL: "https://today.duke.edu/2020/08/first-day-classes-start-masks-distancing-and-vigorous-classrooms"
backgroundImageURL: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=80"
category: "education"
g1Questionnaire:
  - questionType: "INSTRUCTION"
    title: "This is an instruction"
    prompt: "Provide instructional information in this step."
    isOptional: false
  - questionType: "SINGLE CHOICE"
    title: "Q1: Education trivia"
    prompt: "This is a question to ask about higher-ed?"
    choices:
      - "Duke"
      - "Blue devils"
      - "rules"
      - "GTHC"
    correctAnswer: "GTHC"
    isOptional: false
g2Questionnaire:
  - questionType: "INSTRUCTION"
    title: "This is an instruction"
    prompt: "Provide instructional information in this step."
    isOptional: false
  - questionType: "SINGLE CHOICE"
    title: "Q1: Dummy"
    prompt: "You can define another set of questions for the other game group."
    choices:
      - "A"
      - "B"
      - "C"
      - "D"
    correctAnswer: "A"
    isOptional: false
```
